# Generated by Django 6.1 on 2026-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=4, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
