# Generated by Django 6.1 on 2026-08-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_imgcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='imagesbrand',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
